version: '2.4'
services:
  fmdns01:
    image: adlp/famindocker:02
    container_name: ${NAMECOCL:-fmdns01}.dns.${DOMAIN?err}
    hostname: ${NAMECL?err}
    env_file:
      - ./env-fmclient.env
    ports:
      - ${SSHLIP:-0.0.0.0}:${SSHCLTCP?err}:22
      - ${DNSLIP:-0.0.0.0}:${DNSCLTCP?err}:53/tcp
      - ${DNSLIP:-0.0.0.0}:${DNSCLUDP?err}:53/udp
    environment:
      - FMMTH=s
    extra_hosts:
      - ${FMURL?err}:${WUIIP?err}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/${NAMECL?err}/fm:/usr/local/facileManager
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/${NAMECL?err}/var+cache+bind:/var/cache/bind
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/${NAMECL?err}/var+log:/var/log
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/${NAMECL?err}/etc+bind:/etc/bind
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/${NAMECL?err}/home:/home
    logging:
      driver: syslog
      options:
        syslog-address: udp://127.0.0.1:514
        syslog-facility: local0
        tag: fmdns01.dns.${DOMAIN?err}
    restart: always
