version: '2.4'
services:
  fmmaster:
    build:
      context: ${DOCKERROOT}/build
      dockerfile: Dockerfile_fms_02
    image: adlp/famindocker:${DOCTAG:-latest}
    container_name: dns.${DOMAIN?err}
    hostname: dns.${DOMAIN?err}
    env_file:
      - ./env-fmmaster.env
    ports:
      - ${WUILIP:-0.0.0.0}:${WUITCP?err}:80
    volumes:
      - /etc/timezone:/etc/timezone;ro
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/master/appli:/var/www/
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/master/var+log:/var/log/
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/master/tmp:/tmp/
    extra_hosts:
      - ${FMURL?err}:${WUIIP?err}
#    logging:
#      driver: syslog
#      options:
#        syslog-address: udp://127.0.0.1:514
#        syslog-facility: local0
#        tag: dns.${DOMAIN?err}
    restart: always
  mysql:
    image: mysql:5.7-debian
    container_name: db.dns.${DOMAIN?err}
    hostname: db.dns.${DOMAIN?err}
    env_file:
      - ./env-fmmaster.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/db:/var/lib/mysql
#    logging:
#      driver: syslog
#      options:
#        syslog-address: udp://127.0.0.1:514
#        syslog-facility: local0
#        tag: db.dns.${DOMAIN?err}
    restart: always
  fmdns00:
    image: adlp/famindocker:${DOCTAG:-latest}
    container_name: ${NAMECOCL:-fmdns00}.dns.${DOMAIN?err}
    hostname: ${NAMECOCL:-fmdns00}.dns.${DOMAIN?err}
    env_file:
      - ./env-fmclient.env
    ports:
      - ${SSHLIP:-0.0.0.0}:${SSHCLTCP?err}:22
      - ${DNSLIP:-0.0.0.0}:${DNSCLTCP?err}:53/tcp
      - ${DNSLIP:-0.0.0.0}:${DNSCLUDP?err}:53/udp
    extra_hosts:
      - ${FMURL?err}:${WUIIP?err}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/dns00/fm:/usr/local/facileManager
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/dns00/var+cache+bind:/var/cache/bind
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/dns00/var+log:/var/log
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/dns00/etc+bind:/etc/bind
      - ${DOCKERROOT?err}/dns.${DOMAIN?err}/fm/dns00/home:/home
#    logging:
#      driver: syslog
#      options:
#        syslog-address: udp://127.0.0.1:514
#        syslog-facility: local0
#        tag: fmdns00.dns.${DOMAIN?err}
    restart: always
